<a href="https://colab.research.google.com/github/Gokulvasan-V/pandas/blob/main/Guvi_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Import CSV file

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Guvi_python/Guvi Premium courses/Pandas/Dataset/sales_information.csv')
df_copy = pd.copy(df)

In [3]:
df.shape

(20, 6)

In [4]:
df.columns

Index(['Country', 'Region', 'Sales Person', 'Date of Purchase', 'Total',
       'Quantity'],
      dtype='object')

In [5]:
df.head()

     Country Region Sales Person    Date of Purchase   Total  Quantity
0      India  North         John  12/19/2017 0:00:00  100000       567
1         US  North         Bill   6/25/2014 0:00:00  120000      3000
2         UK  North       Thomas   9/12/2010 0:00:00  140000       345
3  Australia   East         John   9/30/2011 0:00:00  160000      1000
4     Africa   East         Bill  11/20/2016 0:00:00  180000       123

In [6]:
df.tail()

      Country Region Sales Person    Date of Purchase   Total  Quantity
15         US   West         John   4/29/2015 0:00:00  220000        90
16         UK   West         Bill   4/15/2012 0:00:00  240000        90
17  Australia   West       Thomas  10/18/2016 0:00:00  260000        90
18     Africa  North         John   9/30/2012 0:00:00  140000        85
19  Singapore  North         Bill    1/7/2013 0:00:00  150000        85

In [7]:
df.describe()

              Total     Quantity
count  2.000000e+01    20.000000
mean   1.502500e+06   977.900000
std    5.769280e+06  1761.923497
min    1.000000e+05    85.000000
25%    1.400000e+05    90.000000
50%    1.700000e+05   505.500000
75%    2.250000e+05  1000.000000
max    2.600000e+07  7890.000000

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Country           20 non-null     object
 1   Region            20 non-null     object
 2   Sales Person      20 non-null     object
 3   Date of Purchase  20 non-null     object
 4   Total             20 non-null     int64
 5   Quantity          20 non-null     int64
dtypes: int64(2), object(4)
memory usage: 1.1+ KB

#### Filer Columns

In [9]:
print(df['Country'] )

0         India
1            US
2            UK
3     Australia
4        Africa
5     Singapore
6       Mylasia
7         India
8            US
9            UK
10    Australia
11       Africa
12    Singapore
13      Mylasia
14        India
15           US
16           UK
17    Australia
18       Africa
19    Singapore
Name: Country, dtype: object

In [10]:
print(type(df['Country']))

<class 'pandas.core.series.Series'>

In [11]:
# df['Country', 'Region'] # It will show error because that is 3-D

df[['Country', 'Region']]

      Country Region
0       India  North
1          US  North
2          UK  North
3   Australia   East
4      Africa   East
5   Singapore   East
6     Mylasia   West
7       India   West
8          US   West
9          UK  North
10  Australia  North
11     Africa  North
12  Singapore   East
13    Mylasia   East
14      India   East
15         US   West
16         UK   West
17  Australia   West
18     Africa  North
19  Singapore  North

In [12]:
print(type(df[['Country', 'Region']]))

<class 'pandas.core.frame.DataFrame'>

In [13]:
df[['Country']]

      Country
0       India
1          US
2          UK
3   Australia
4      Africa
5   Singapore
6     Mylasia
7       India
8          US
9          UK
10  Australia
11     Africa
12  Singapore
13    Mylasia
14      India
15         US
16         UK
17  Australia
18     Africa
19  Singapore

In [14]:
print(type(df[['Country']]))

<class 'pandas.core.frame.DataFrame'>

#### Filter Rows

In [15]:
df.iloc[0:3]

  Country Region Sales Person    Date of Purchase   Total  Quantity
0   India  North         John  12/19/2017 0:00:00  100000       567
1      US  North         Bill   6/25/2014 0:00:00  120000      3000
2      UK  North       Thomas   9/12/2010 0:00:00  140000       345

In [16]:
df[['Country','Region']].iloc[0:3]

  Country Region
0   India  North
1      US  North
2      UK  North

**Filter rows based on some specific value**

In [17]:
# df[df['Country'] == 'India' & df['Total'] >= 200000] # it will show error

df[(df['Country'] == 'India') & (df['Total'] >= 200000)]

   Country Region Sales Person   Date of Purchase   Total  Quantity
7    India   West         Bill   4/8/2014 0:00:00  240000       200
14   India   East       Thomas  11/9/2010 0:00:00  200000        90

In [18]:
df

      Country Region Sales Person    Date of Purchase     Total  Quantity
0       India  North         John  12/19/2017 0:00:00    100000       567
1          US  North         Bill   6/25/2014 0:00:00    120000      3000
2          UK  North       Thomas   9/12/2010 0:00:00    140000       345
3   Australia   East         John   9/30/2011 0:00:00    160000      1000
4      Africa   East         Bill  11/20/2016 0:00:00    180000       123
5   Singapore   East       Thomas   8/17/2016 0:00:00    200000      1000
6     Mylasia   West         John   9/15/2014 0:00:00   1000000      7890
7       India   West         Bill    4/8/2014 0:00:00    240000       200
8          US   West       Thomas  11/25/2016 0:00:00  26000000      1000
9          UK  North         John  12/15/2012 0:00:00    100000      1000
10  Australia  North         Bill    9/6/2011 0:00:00    120000       567
11     Africa  North       Thomas   12/8/2017 0:00:00    140000      1000
12  Singapore   East         John   7/30/2014 0:00:00    160000       892
13    Mylasia   East         Bill   10/8/2016 0:00:00    180000       444
14      India   East       Thomas   11/9/2010 0:00:00    200000        90
15         US   West         John   4/29/2015 0:00:00    220000        90
16         UK   West         Bill   4/15/2012 0:00:00    240000        90
17  Australia   West       Thomas  10/18/2016 0:00:00    260000        90
18     Africa  North         John   9/30/2012 0:00:00    140000        85
19  Singapore  North         Bill    1/7/2013 0:00:00    150000        85

How to add New Colums and Rows in Existing DataFrame (or) Dataset

In [19]:
# adding new column

calls_made = [10,60] *10
calls_made

[10,
 60,
 10,
 60,
 10,
 60,
 10,
 60,
 10,
 60,
 10,
 60,
 10,
 60,
 10,
 60,
 10,
 60,
 10,
 60]

In [20]:
df['Calls_made'] = calls_made
df.head()

,Country,Region,Sales Person,Date of Purchase,Total,Quantity,Calls_made
0,India,North,John,12/19/2017 0:00:00,100000,567,10
1,US,North,Bill,6/25/2014 0:00:00,120000,3000,60
2,UK,North,Thomas,9/12/2010 0:00:00,140000,345,10
3,Australia,East,John,9/30/2011 0:00:00,160000,1000,60
4,Africa,East,Bill,11/20/2016 0:00:00,180000,123,10

In [21]:
type(df['Date of Purchase'][0])

str

In [22]:
# Adding New Row

new_row = [['china', 'East', 'Jim', '12/19/2017 0:00:00', 70000, 700, 40 ]] # Because this is 2D array, that's why we are adding dual list

new_df_row = pd.DataFrame(new_row, columns = df.columns.values)
df.append(new_df_row,
          ignore_index = True) # ignore index --> for continuity index value, Otherwise index will start from 0

<ipython-input-22-a5fbf4afc6c1>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df.append(new_df_row,

,Country,Region,Sales Person,Date of Purchase,Total,Quantity,Calls_made
0,India,North,John,12/19/2017 0:00:00,100000,567,10
1,US,North,Bill,6/25/2014 0:00:00,120000,3000,60
2,UK,North,Thomas,9/12/2010 0:00:00,140000,345,10
3,Australia,East,John,9/30/2011 0:00:00,160000,1000,60
4,Africa,East,Bill,11/20/2016 0:00:00,180000,123,10
5,Singapore,East,Thomas,8/17/2016 0:00:00,200000,1000,60
6,Mylasia,West,John,9/15/2014 0:00:00,1000000,7890,10
7,India,West,Bill,4/8/2014 0:00:00,240000,200,60
8,US,West,Thomas,11/25/2016 0:00:00,26000000,1000,10
9,UK,North,John,12/15/2012 0:00:00,100000,1000,60
10,Australia,North,Bill,9/6/2011 0:00:00,120000,567,10
11,Africa,North,Thomas,12/8/2017 0:00:00,140000,1000,60
12,Singapore,East,John,7/30/2014 0:00:00,160000,892,10
13,Mylasia,East,Bill,10/8/2016 0:00:00,180000,444,60
14,India,East,Thomas,11/9/2010 0:00:00,200000,90,10
15,US,West,John,4/29/2015 0:00:00,220000,90,60
16,UK,West,Bill,4/15/2012 0:00:00,240000,90,10
17,Australia,West,Thomas,10/18/2016 0:00:00,260000,90,60
18,Africa,North,John,9/30/2012 0:00:00,140000,85,10
19,Singapore,North,Bill,1/7/2013 0:00:00,150000,85,60
20,china,East,Jim,12/19/2017 0:00:00,70000,700,40

**Sorting the DataFrame**

here i am going to modify some changes

In [23]:
po_number = [int(f'1000{i}') for i in range(20)]
po_number

[10000,
 10001,
 10002,
 10003,
 10004,
 10005,
 10006,
 10007,
 10008,
 10009,
 100010,
 100011,
 100012,
 100013,
 100014,
 100015,
 100016,
 100017,
 100018,
 100019]

In [26]:
import random
random.shuffle(po_number)
po_number

[100018,
 10002,
 10007,
 100014,
 10003,
 10009,
 100010,
 100013,
 100017,
 100019,
 100015,
 10008,
 100011,
 10000,
 100016,
 10001,
 10005,
 100012,
 10004,
 10006]

In [31]:
df['po_number'] = po_number
df.set_index('po_number', inplace = True)
df.head()

,Country,Region,Sales Person,Date of Purchase,Total,Quantity,Calls_made
po_number,,,,,,,
100018,India,North,John,12/19/2017 0:00:00,100000,567,10
10002,US,North,Bill,6/25/2014 0:00:00,120000,3000,60
10007,UK,North,Thomas,9/12/2010 0:00:00,140000,345,10
100014,Australia,East,John,9/30/2011 0:00:00,160000,1000,60
10003,Africa,East,Bill,11/20/2016 0:00:00,180000,123,10

Sorting index column

In [33]:
df.sort_index(inplace = True)
df.head()

,Country,Region,Sales Person,Date of Purchase,Total,Quantity,Calls_made
po_number,,,,,,,
10000,Mylasia,East,Bill,10/8/2016 0:00:00,180000,444,60
10001,US,West,John,4/29/2015 0:00:00,220000,90,60
10002,US,North,Bill,6/25/2014 0:00:00,120000,3000,60
10003,Africa,East,Bill,11/20/2016 0:00:00,180000,123,10
10004,Africa,North,John,9/30/2012 0:00:00,140000,85,10

In [46]:
df.sort_index(ascending = False) # ascending = False ---> Descending order

,Country,Region,Sales Person,Date of Purchase,Total,Quantity,Calls_made
po_number,,,,,,,
100019,UK,North,John,12/15/2012 0:00:00,100000,1000,60
100018,India,North,John,12/19/2017 0:00:00,100000,567,10
100017,US,West,Thomas,11/25/2016 0:00:00,26000000,1000,10
100016,India,East,Thomas,11/9/2010 0:00:00,200000,90,10
100015,Australia,North,Bill,9/6/2011 0:00:00,120000,567,10
100014,Australia,East,John,9/30/2011 0:00:00,160000,1000,60
100013,India,West,Bill,4/8/2014 0:00:00,240000,200,60
100012,Australia,West,Thomas,10/18/2016 0:00:00,260000,90,60
100011,Singapore,East,John,7/30/2014 0:00:00,160000,892,10
100010,Mylasia,West,John,9/15/2014 0:00:00,1000000,7890,10
10009,Singapore,East,Thomas,8/17/2016 0:00:00,200000,1000,60
10008,Africa,North,Thomas,12/8/2017 0:00:00,140000,1000,60
10007,UK,North,Thomas,9/12/2010 0:00:00,140000,345,10
10006,Singapore,North,Bill,1/7/2013 0:00:00,150000,85,60
10005,UK,West,Bill,4/15/2012 0:00:00,240000,90,10
10004,Africa,North,John,9/30/2012 0:00:00,140000,85,10
10003,Africa,East,Bill,11/20/2016 0:00:00,180000,123,10
10002,US,North,Bill,6/25/2014 0:00:00,120000,3000,60
10001,US,West,John,4/29/2015 0:00:00,220000,90,60
10000,Mylasia,East,Bill,10/8/2016 0:00:00,180000,444,60

Sorting values column

In [37]:
df.columns

Index(['Country', 'Region', 'Sales Person', 'Date of Purchase', 'Total',
       'Quantity', 'Calls_made'],
      dtype='object')

In [41]:
df.sort_values('Country',inplace = True)
df.head(10)

,Country,Region,Sales Person,Date of Purchase,Total,Quantity,Calls_made
po_number,,,,,,,
10003,Africa,East,Bill,11/20/2016 0:00:00,180000,123,10
10004,Africa,North,John,9/30/2012 0:00:00,140000,85,10
10008,Africa,North,Thomas,12/8/2017 0:00:00,140000,1000,60
100014,Australia,East,John,9/30/2011 0:00:00,160000,1000,60
100015,Australia,North,Bill,9/6/2011 0:00:00,120000,567,10
100012,Australia,West,Thomas,10/18/2016 0:00:00,260000,90,60
100016,India,East,Thomas,11/9/2010 0:00:00,200000,90,10
100018,India,North,John,12/19/2017 0:00:00,100000,567,10
100013,India,West,Bill,4/8/2014 0:00:00,240000,200,60
100010,Mylasia,West,John,9/15/2014 0:00:00,1000000,7890,10

In [42]:
df.sort_values(['Country', 'Region'],inplace = True)
df.head(10)

,Country,Region,Sales Person,Date of Purchase,Total,Quantity,Calls_made
po_number,,,,,,,
10003,Africa,East,Bill,11/20/2016 0:00:00,180000,123,10
10004,Africa,North,John,9/30/2012 0:00:00,140000,85,10
10008,Africa,North,Thomas,12/8/2017 0:00:00,140000,1000,60
100014,Australia,East,John,9/30/2011 0:00:00,160000,1000,60
100015,Australia,North,Bill,9/6/2011 0:00:00,120000,567,10
100012,Australia,West,Thomas,10/18/2016 0:00:00,260000,90,60
100016,India,East,Thomas,11/9/2010 0:00:00,200000,90,10
100018,India,North,John,12/19/2017 0:00:00,100000,567,10
100013,India,West,Bill,4/8/2014 0:00:00,240000,200,60
10000,Mylasia,East,Bill,10/8/2016 0:00:00,180000,444,60

In [44]:
df.sort_values(['Country', 'Region'], ascending= False)

,Country,Region,Sales Person,Date of Purchase,Total,Quantity,Calls_made
po_number,,,,,,,
10001,US,West,John,4/29/2015 0:00:00,220000,90,60
100017,US,West,Thomas,11/25/2016 0:00:00,26000000,1000,10
10002,US,North,Bill,6/25/2014 0:00:00,120000,3000,60
10005,UK,West,Bill,4/15/2012 0:00:00,240000,90,10
10007,UK,North,Thomas,9/12/2010 0:00:00,140000,345,10
100019,UK,North,John,12/15/2012 0:00:00,100000,1000,60
10006,Singapore,North,Bill,1/7/2013 0:00:00,150000,85,60
10009,Singapore,East,Thomas,8/17/2016 0:00:00,200000,1000,60
100011,Singapore,East,John,7/30/2014 0:00:00,160000,892,10
100010,Mylasia,West,John,9/15/2014 0:00:00,1000000,7890,10
10000,Mylasia,East,Bill,10/8/2016 0:00:00,180000,444,60
100013,India,West,Bill,4/8/2014 0:00:00,240000,200,60
100018,India,North,John,12/19/2017 0:00:00,100000,567,10
100016,India,East,Thomas,11/9/2010 0:00:00,200000,90,10
100012,Australia,West,Thomas,10/18/2016 0:00:00,260000,90,60
100015,Australia,North,Bill,9/6/2011 0:00:00,120000,567,10
100014,Australia,East,John,9/30/2011 0:00:00,160000,1000,60
10004,Africa,North,John,9/30/2012 0:00:00,140000,85,10
10008,Africa,North,Thomas,12/8/2017 0:00:00,140000,1000,60
10003,Africa,East,Bill,11/20/2016 0:00:00,180000,123,10